### ISSUE TITLE
Upload failed: Error: COS is not configured yet

### ISSUE THREAD

**Issue by duyuankai1992** [frostming/Flog#33]
![image](https://user-images.githubusercontent.com/30469067/127727864-c050a8a6-ae0b-402d-a0bd-5a003c94e4be.png)
很抱歉又打扰到您，我上传本地图片时遇到Upload failed: Error: COS is not configured yet，请问我需要配置哪里。

**Comment by frostming** [comment]
后台 - Integration里配置下COS（腾讯云的对象存储）

**Comment by frostming** [comment]
后台 - Integration里配置下COS（腾讯云的对象存储）

**Comment by duyuankai1992** [comment]
@frostming 
![image](https://user-images.githubusercontent.com/30469067/127731256-0fc337d1-01c5-4180-9938-a6137f61fcc6.png)
是不是配置一下这个东西

**Comment by frostming** [comment]
在界面上配置啊
