### ISSUE TITLE
ERROR: Service 'web' failed to build: The command '/bin/sh -c pdm sync -s postgres --prod' returned a non-zero code: 2

### ISSUE THREAD

**Issue by duyuankai1992** [frostming/Flog#35]
运行docker-compose up --build -d 出现这个错误
![image](https://user-images.githubusercontent.com/30469067/147059993-bc2ea82d-d9f0-43b8-a990-6d7cd3489002.png)
![image](https://user-images.githubusercontent.com/30469067/147060872-49560fda-4e36-42c0-b3db-c603fa1fdf98.png)
单独运行 pdm sync -s postgres --prod 
![image](https://user-images.githubusercontent.com/30469067/147060950-90be4e3c-3530-4e40-b330-2d94ae1223f8.png)
我该怎么修改哈

**Comment by frostming** [comment]
pdm新版本`-s` 改成 `-G`了
