### ISSUE TITLE
docker file报错了

### ISSUE THREAD

**Issue by lwl972449576** [frostming/Flog#37]
#RUN pdm  -s  postgres  --prod
 => ERROR [ 6/10] RUN pdm sync -s postgres --prod                                                                                                                                                      0.8s
------
 > [ 6/10] RUN pdm sync -s postgres --prod:
#0 0.687 Usage: pdm [-h] [-V] [-c CONFIG] [-v] [-I] [--pep582 [SHELL]]
#0 0.687            {add,build,cache,completion,config,export,import,info,init,install,list,lock,plugin,publish,remove,run,search,show,sync,update,use,venv}
#0 0.687            ...
#0 0.687 pdm: error: unrecognized arguments: -s postgres

这里报错了，是因为pdm更新了吗，不会用啊  ，哥，可以说下怎么改这行吗

**Comment by frostming** [comment]
已经更新了
